# Generated by Django 5.2.3 on 2025-06-26 08:35

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='userkyc',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_images/default.png', null=True, upload_to=users.models.user_profile_image_path),
        ),
        migrations.AlterField(
            model_name='userkyc',
            name='document_back',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_kyc_document_path),
        ),
        migrations.AlterField(
            model_name='userkyc',
            name='document_front',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_kyc_document_path),
        ),
    ]
