# Generated by Django 5.2.3 on 2025-06-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
